# Generated by Django 4.2.5 on 2023-10-31 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="potdata",
            name="gps_time",
        ),
        migrations.AddField(
            model_name="potdata",
            name="gps_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
