# Generated by Django 4.2.5 on 2023-11-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_remove_potdata_gps_time_potdata_gps_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="potdata",
            name="gps_date",
        ),
    ]
